//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mobile_details()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public int mobileId { get; set; }
        public int user_id { get; set; }
        public string mobileName { get; set; }
        public string description { get; set; }
        public int price { get; set; }
        public int stock_quantity { get; set; }
        public string image_name { get; set; }
        public Nullable<int> order_quantity { get; set; }
    
        public virtual user_details user_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
    }
}
